"""add donation status and checkout_request_id

Revision ID: fa4ccfd5f0ae
Revises: 79e03d322b32
Create Date: 2026-07-11 20:19:46.969761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4ccfd5f0ae'
down_revision = '79e03d322b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='completed'))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint('uq_donations_checkout_request_id', ['checkout_request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
