"""add rewards, user_rewards, and recurring_donations

Revision ID: fd8ffe87ad69
Revises: 5af72e7c4dce
Create Date: 2026-07-11 21:42:45.180570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8ffe87ad69'
down_revision = '5af72e7c4dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('points_required', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('next_run_date', sa.Date(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cause_id'], ['causes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_donation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_donations_recurring_donation_id', 'recurring_donations', ['recurring_donation_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donations_recurring_donation_id', type_='foreignkey')
        batch_op.drop_column('recurring_donation_id')

    op.drop_table('recurring_donations')
    op.drop_table('user_rewards')
    op.drop_table('rewards')
    # ### end Alembic commands ###
